#!/bin/bash

virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
export FLASK_APP=app.py

mkdir database
flask db init
flask db migrate
flask db upgrade

python tests/tests.py

deactivate
