"""empty message

Revision ID: 07e53293f22a
Revises: 
Create Date: 2022-01-24 19:18:57.645896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e53293f22a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dodawanie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liczba1', sa.Text(), nullable=True),
    sa.Column('liczba2', sa.Text(), nullable=True),
    sa.Column('wynik', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dodawanie_timestamp'), 'dodawanie', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_timestamp'), 'users', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_timestamp'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dodawanie_timestamp'), table_name='dodawanie')
    op.drop_table('dodawanie')
    # ### end Alembic commands ###
